sudo: required

services:
  - docker

before_install:
  - docker build -t tcheryph/container-x -f Dockerfile.dev .

script:
  - docker run -e CI=true tcheryph/container-x npm run test

deploy:   
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Dockerfrontend"
  env: "Dockerfrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-132750828057"
  bucket_path: "Dockerfrontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY